language: python
python: 2.7
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - texlive-latex-extra
    - dvipng
    - texlive-latex-recommended
    - texlive-xetex
    - latex-xcolor
install: pip install Pygments
script:
- mkdir pdf
- bin/appendix > report/appendix.tex
- xelatex --synctex=2 --output-directory=pdf --interaction=nonstopmode -shell-escape report/report.tex
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file: pdf/report.pdf
  target_branch: report
  on:
    branch: master
