language: python
python: 2.7
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - texlive-latex-extra
    - dvipng
    - texlive-latex-recommended
    - texlive-xetex
    - latex-xcolor
    - lmodern
install: pip install Pygments
script:
- mkdir pdf
- bin/appendix > report/appendix.tex
- cd report
- xelatex --synctex=2 --output-directory=../pdf --interaction=nonstopmode -shell-escape report.tex || true # Tables require regeneration
- xelatex --synctex=2 --output-directory=../pdf --interaction=nonstopmode -shell-escape report.tex
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  target_branch: report
  on:
    branch: master
